#!/usr/bin/env python3
"""Lift the pure routing items out of agents/agent-core/src/groups.rs.

Same principle as scripts/group-routing-check/extract.py: copy the real source
rather than restate it, because a benchmark that retyped the group table would
measure the copy instead of the thing that ships.

Differs from that extractor in one way that matters here. This harness is run
against *arbitrary past revisions* to backfill datapoints, so it must degrade
rather than die: a revision predating a given item simply yields a table without
it, and the caller decides whether what came back is enough to measure. Exit
code 2 means "no group table at this revision" — the runner reads that as
"measure SkillRet only", not as a failure.
"""
import re
import sys

# (declaration prefix, required). A missing optional item is dropped silently;
# a missing required one means this revision has no routable table.
WANTED = [
    ("const UNGROUPED", True),
    ("pub struct ToolGroup", True),
    ("pub fn all()", True),
    ("fn find(", True),
    ("const PREFIX_RULES", False),
    ("const COMPONENT_CAP_PREFIX", False),
    ("pub fn component_group(", False),
    ("pub fn builtin_active(", False),
    ("fn tokens(", True),
    ("pub fn score(", True),
    ("fn tag_present(", False),
    ("fn in_table_order(", False),
    ("const SKILL_TAG_PREFIX", False),
]


def find_item(lines, want):
    """Return the source of the top-level item declared with `want`, or None."""
    start = None
    for i, line in enumerate(lines):
        if line.startswith(want):
            start = i
            break
    if start is None:
        return None

    # Keep the doc comment: the rationale is most of the value of this source.
    head = start
    while head > 0 and (
        lines[head - 1].startswith("///") or lines[head - 1].startswith("//")
    ):
        head -= 1

    # A const on one line ends at its semicolon; anything else ends when the
    # brackets it opened close again.
    if want.startswith("const") and lines[start].rstrip().endswith(";"):
        end = start
    else:
        end = start
        depth = 0
        seen = False
        for i in range(start, len(lines)):
            depth += (
                lines[i].count("{")
                + lines[i].count("[")
                - lines[i].count("}")
                - lines[i].count("]")
            )
            if "{" in lines[i] or "[" in lines[i]:
                seen = True
            if seen and depth <= 0:
                end = i
                break
    return "\n".join(lines[head : end + 1])


def main():
    src = open(sys.argv[1]).read()
    lines = src.split("\n")

    out, missing = [], []
    for want, required in WANTED:
        item = find_item(lines, want)
        if item is None:
            if required:
                missing.append(want)
            continue
        out.append(item)

    if missing:
        sys.stderr.write(
            "no routable group table at this revision; missing: %s\n"
            % ", ".join(missing)
        )
        sys.exit(2)

    body = "\n\n".join(out)
    # Private within groups.rs, whose module boundary is the crate. The harness
    # imports across a module, so promote rather than restate.
    body = re.sub(r"^(const|fn|struct) ", r"pub \1 ", body, flags=re.M)
    # sys::log is a host import. In a harness a gap should be loud, not absent.
    body = re.sub(r"sys::log\(\s*LogLevel::\w+,", "log_warn(", body)

    print("// GENERATED by extract.py from agents/agent-core/src/groups.rs.")
    print("// Do not edit: this is a copy of the shipping router.")
    print("#![allow(dead_code, unused_imports)]")
    print()
    print('pub fn log_warn(msg: &str) { eprintln!("[log] {}", msg.trim()); }')
    print()
    print(body)


if __name__ == "__main__":
    main()
